min_particles: 500
max_particles: 2000
update_min_d: 0.2
update_min_a: 0.1
resample_interval: 1
transform_tolerance: 0.1

laser_max_beams: 60
laser_max_range: 8.0
laser_z_hit: 0.5
laser_sigma_hit: 0.2
laser_z_short: 0.1
laser_lambda_short: 0.1
laser_z_max: 0.05
laser_z_rand: 0.3
laser_likelihood_max_dist: 2.0

odom_alpha1: 0.2
odom_alpha2: 0.2
odom_alpha3: 0.2
odom_alpha4: 0.2
odom_alpha5: 0.1

initial_pose_x: 0.0
initial_pose_y: 0.0
initial_pose_a: 0.0
initial_cov_xx: 0.5
initial_cov_yy: 0.5
initial_cov_aa: 0.2

